### PR TITLE
Remove intern from title.

### PR DESCRIPTION
**Pull request by jakobw**
I'm not an intern :)

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
https://wikimedia.de/wiki/Mitarbeiter says

> Software-Entwickler (Werkstudent) 

so that is wrong?

**Comment by manicki** [comment]
Werkstudent = Working Student

Intern seems to be called "Praktikum" on that German page.

**Comment by JeroenDeDauw** [comment]
And `Working Student != Intern`?

**Comment by manicki** [comment]
Apparently.

**Pull request merged**
