### PR TITLE
Use the correct media type for video(video/webm)

### PR DESCRIPTION
**Pull request by Abbe98**

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Hah, nice catch. Thanks!

**Comment by Abbe98** [comment]
@JeroenDeDauw it won't play with the wrong media type... :mag:

**Comment by JeroenDeDauw** [comment]
In what browser? Worked fine for me in FailFox

**Comment by Abbe98** [comment]
I used Opera but I'm quite sure that it affected all Chromium based browsers...

**Pull request merged**
