### PR TITLE
Remove hover effects on project logos

### PR DESCRIPTION
**Pull request by Abbe98**
It makes them appear as interactive/clickable.

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Thanks

**Comment by JeroenDeDauw** [comment]
Follow up: https://github.com/wmde/software.wikimedia.de/commit/3fbe9175de7ef201450e853e086103483ede0d3a

**Comment by Abbe98** [comment]
Woops sorry!

**Comment by JeroenDeDauw** [comment]
That's what CR is for

**Pull request merged**
